apiVersion: v1
kind: ConfigMap
metadata:
  name: model-config
  namespace: lab8
data:
  config.k8s.yaml: |
    spark:
      app_name: OpenFoodFacts-KMeans
      master: local[*]
      driver_memory: 768m
      shuffle_partitions: "8"
      log_level: WARN
    data:
      input_path: data/food_small.parquet
    datamart:
      url: http://datamart:8090
    preprocessing:
      min_non_null_ratio: 0.9
      target_rows: 20000
      imputer_strategy: median
    training:
      k: 2
      seed: 42
      metric_name: silhouette
      distance_measure: squaredEuclidean
